CREATE SEQUENCE WORLD_CUP_SEQ;

CREATE TABLE WORLD_CUP (
  ID_WORLD_CUP BIGINT PRIMARY KEY,
  EDITION INT UNIQUE NOT NULL,
  HOST VARCHAR(30) NOT NULL
);


CREATE SEQUENCE TEAM_SEQ;

CREATE TABLE TEAM (
  ID_TEAM BIGINT PRIMARY KEY,
  CODE VARCHAR(3) UNIQUE NOT NULL,
  NAME VARCHAR(30) NOT NULL
);


CREATE SEQUENCE MATCH_SEQ;

CREATE TABLE MATCH (
  ID_MATCH BIGINT PRIMARY KEY,
  ID_WORLD_CUP BIGINT NOT NULL,
  ID_TEAM_A BIGINT NOT NULL,
  ID_TEAM_B BIGINT NOT NULL,
  GOALS_TEAM_A INT,
  GOALS_TEAM_B INT,
  SCHEDULE TIMESTAMP,
  FOREIGN KEY(ID_WORLD_CUP) REFERENCES WORLD_CUP(ID_WORLD_CUP),
  FOREIGN KEY(ID_TEAM_A) REFERENCES TEAM(ID_TEAM),
  FOREIGN KEY(ID_TEAM_B) REFERENCES TEAM(ID_TEAM)
);
